/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SoiRouteImport } from './routes/soi'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedServicesRouteImport } from './routes/_authenticated/services'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedPosRouteImport } from './routes/_authenticated/pos'
import { Route as AuthenticatedMySalesRouteImport } from './routes/_authenticated/my-sales'
import { Route as AuthenticatedMembershipsRouteImport } from './routes/_authenticated/memberships'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCustomersRouteImport } from './routes/_authenticated/customers'
import { Route as AuthenticatedAppointmentsRouteImport } from './routes/_authenticated/appointments'
import { Route as ApiPublicWebsiteAppointmentRouteImport } from './routes/api/public/website-appointment'
import { Route as AuthenticatedCustomersCustomerIdRouteImport } from './routes/_authenticated/customers.$customerId'

const SoiRoute = SoiRouteImport.update({
  id: '/soi',
  path: '/soi',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedServicesRoute = AuthenticatedServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPosRoute = AuthenticatedPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMySalesRoute = AuthenticatedMySalesRouteImport.update({
  id: '/my-sales',
  path: '/my-sales',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMembershipsRoute =
  AuthenticatedMembershipsRouteImport.update({
    id: '/memberships',
    path: '/memberships',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCustomersRoute = AuthenticatedCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppointmentsRoute =
  AuthenticatedAppointmentsRouteImport.update({
    id: '/appointments',
    path: '/appointments',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiPublicWebsiteAppointmentRoute =
  ApiPublicWebsiteAppointmentRouteImport.update({
    id: '/api/public/website-appointment',
    path: '/api/public/website-appointment',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedCustomersCustomerIdRoute =
  AuthenticatedCustomersCustomerIdRouteImport.update({
    id: '/$customerId',
    path: '/$customerId',
    getParentRoute: () => AuthenticatedCustomersRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/soi': typeof SoiRoute
  '/appointments': typeof AuthenticatedAppointmentsRoute
  '/customers': typeof AuthenticatedCustomersRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/memberships': typeof AuthenticatedMembershipsRoute
  '/my-sales': typeof AuthenticatedMySalesRoute
  '/pos': typeof AuthenticatedPosRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/services': typeof AuthenticatedServicesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/customers/$customerId': typeof AuthenticatedCustomersCustomerIdRoute
  '/api/public/website-appointment': typeof ApiPublicWebsiteAppointmentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/soi': typeof SoiRoute
  '/appointments': typeof AuthenticatedAppointmentsRoute
  '/customers': typeof AuthenticatedCustomersRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/memberships': typeof AuthenticatedMembershipsRoute
  '/my-sales': typeof AuthenticatedMySalesRoute
  '/pos': typeof AuthenticatedPosRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/services': typeof AuthenticatedServicesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/customers/$customerId': typeof AuthenticatedCustomersCustomerIdRoute
  '/api/public/website-appointment': typeof ApiPublicWebsiteAppointmentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/soi': typeof SoiRoute
  '/_authenticated/appointments': typeof AuthenticatedAppointmentsRoute
  '/_authenticated/customers': typeof AuthenticatedCustomersRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/memberships': typeof AuthenticatedMembershipsRoute
  '/_authenticated/my-sales': typeof AuthenticatedMySalesRoute
  '/_authenticated/pos': typeof AuthenticatedPosRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/services': typeof AuthenticatedServicesRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/customers/$customerId': typeof AuthenticatedCustomersCustomerIdRoute
  '/api/public/website-appointment': typeof ApiPublicWebsiteAppointmentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/soi'
    | '/appointments'
    | '/customers'
    | '/dashboard'
    | '/memberships'
    | '/my-sales'
    | '/pos'
    | '/reports'
    | '/services'
    | '/settings'
    | '/customers/$customerId'
    | '/api/public/website-appointment'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/soi'
    | '/appointments'
    | '/customers'
    | '/dashboard'
    | '/memberships'
    | '/my-sales'
    | '/pos'
    | '/reports'
    | '/services'
    | '/settings'
    | '/customers/$customerId'
    | '/api/public/website-appointment'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/soi'
    | '/_authenticated/appointments'
    | '/_authenticated/customers'
    | '/_authenticated/dashboard'
    | '/_authenticated/memberships'
    | '/_authenticated/my-sales'
    | '/_authenticated/pos'
    | '/_authenticated/reports'
    | '/_authenticated/services'
    | '/_authenticated/settings'
    | '/_authenticated/customers/$customerId'
    | '/api/public/website-appointment'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SoiRoute: typeof SoiRoute
  ApiPublicWebsiteAppointmentRoute: typeof ApiPublicWebsiteAppointmentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/soi': {
      id: '/soi'
      path: '/soi'
      fullPath: '/soi'
      preLoaderRoute: typeof SoiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/services': {
      id: '/_authenticated/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof AuthenticatedServicesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pos': {
      id: '/_authenticated/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof AuthenticatedPosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/my-sales': {
      id: '/_authenticated/my-sales'
      path: '/my-sales'
      fullPath: '/my-sales'
      preLoaderRoute: typeof AuthenticatedMySalesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/memberships': {
      id: '/_authenticated/memberships'
      path: '/memberships'
      fullPath: '/memberships'
      preLoaderRoute: typeof AuthenticatedMembershipsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/customers': {
      id: '/_authenticated/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthenticatedCustomersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/appointments': {
      id: '/_authenticated/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AuthenticatedAppointmentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/website-appointment': {
      id: '/api/public/website-appointment'
      path: '/api/public/website-appointment'
      fullPath: '/api/public/website-appointment'
      preLoaderRoute: typeof ApiPublicWebsiteAppointmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/customers/$customerId': {
      id: '/_authenticated/customers/$customerId'
      path: '/$customerId'
      fullPath: '/customers/$customerId'
      preLoaderRoute: typeof AuthenticatedCustomersCustomerIdRouteImport
      parentRoute: typeof AuthenticatedCustomersRoute
    }
  }
}

interface AuthenticatedCustomersRouteChildren {
  AuthenticatedCustomersCustomerIdRoute: typeof AuthenticatedCustomersCustomerIdRoute
}

const AuthenticatedCustomersRouteChildren: AuthenticatedCustomersRouteChildren =
  {
    AuthenticatedCustomersCustomerIdRoute:
      AuthenticatedCustomersCustomerIdRoute,
  }

const AuthenticatedCustomersRouteWithChildren =
  AuthenticatedCustomersRoute._addFileChildren(
    AuthenticatedCustomersRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAppointmentsRoute: typeof AuthenticatedAppointmentsRoute
  AuthenticatedCustomersRoute: typeof AuthenticatedCustomersRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMembershipsRoute: typeof AuthenticatedMembershipsRoute
  AuthenticatedMySalesRoute: typeof AuthenticatedMySalesRoute
  AuthenticatedPosRoute: typeof AuthenticatedPosRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedServicesRoute: typeof AuthenticatedServicesRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppointmentsRoute: AuthenticatedAppointmentsRoute,
  AuthenticatedCustomersRoute: AuthenticatedCustomersRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMembershipsRoute: AuthenticatedMembershipsRoute,
  AuthenticatedMySalesRoute: AuthenticatedMySalesRoute,
  AuthenticatedPosRoute: AuthenticatedPosRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedServicesRoute: AuthenticatedServicesRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SoiRoute: SoiRoute,
  ApiPublicWebsiteAppointmentRoute: ApiPublicWebsiteAppointmentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
